//! Lookups between TeX math command names, Greek letters, raw glyphs, and Typst tokens.

use std::collections::BTreeMap;
use std::sync::LazyLock;

use super::super::symbols::{self, Alphabet};

/// Codepoint-to-Typst-name map for raw Unicode math glyphs written directly in the source. It is
/// the inverse of the forward symbol/Greek tables: each command's Unicode rendering (from
/// [`symbols::symbol`]/[`symbols::greek`]) maps to that command's Typst name (from [`SYMBOL_TYPST`]/
/// [`GREEK_TYPST`]).
static GLYPH_TYPST: LazyLock<BTreeMap<char, &'static str>> = LazyLock::new(build_glyph_typst);

/// Name-keyed view of [`SYMBOL_TYPST`] for by-name lookups. On a duplicate name the first table
/// entry wins, so the map answers exactly as a linear scan of the slice would.
pub(crate) static SYMBOL_TYPST_MAP: LazyLock<BTreeMap<&'static str, &'static str>> =
    LazyLock::new(|| {
        let mut map = BTreeMap::new();
        for (name, typst) in SYMBOL_TYPST {
            map.entry(*name).or_insert(*typst);
        }
        map
    });

/// Name-keyed view of [`GREEK_TYPST`], with the same first-entry-wins semantics as [`SYMBOL_TYPST_MAP`].
pub(crate) static GREEK_TYPST_MAP: LazyLock<BTreeMap<&'static str, &'static str>> =
    LazyLock::new(|| {
        let mut map = BTreeMap::new();
        for (name, typst) in GREEK_TYPST {
            map.entry(*name).or_insert(*typst);
        }
        map
    });

fn build_glyph_typst() -> BTreeMap<char, &'static str> {
    let mut map = BTreeMap::new();
    let mut insert = |glyph: &str, typst: &'static str| {
        // only single-codepoint glyphs with a distinct Typst name are reversible; passthroughs dropped
        let mut chars = glyph.chars();
        if let (Some(c), None) = (chars.next(), chars.next())
            && glyph != typst
        {
            map.entry(c).or_insert(typst);
        }
    };
    for (name, typst) in SYMBOL_TYPST {
        if let Some(sym) = symbols::symbol(name) {
            insert(sym.text, typst);
        }
    }
    for (name, typst) in GREEK_TYPST {
        if let Some((glyph, _)) = symbols::greek(name) {
            insert(glyph, typst);
        }
    }
    // double-struck capitals reverse to doubled letters (`ℝ` → `RR`); lowercase and digits stay verbatim
    for (letter, name) in (b'A'..=b'Z').zip(DOUBLE_STRUCK_NAMES) {
        let upper = letter as char;
        if let Some(glyph) = symbols::styled_letter(Alphabet::DoubleStruck, upper)
            && let Some(c) = glyph.chars().next()
            && glyph.chars().nth(1).is_none()
        {
            map.entry(c).or_insert(name);
        }
    }
    map
}

/// The Typst name for each double-struck capital `A`…`Z`: the letter doubled.
const DOUBLE_STRUCK_NAMES: [&str; 26] = [
    "AA", "BB", "CC", "DD", "EE", "FF", "GG", "HH", "II", "JJ", "KK", "LL", "MM", "NN", "OO", "PP",
    "QQ", "RR", "SS", "TT", "UU", "VV", "WW", "XX", "YY", "ZZ",
];

/// The Typst name for a raw Unicode math glyph written directly in the source, or `None` when the
/// glyph carries no dedicated Typst token (it is then emitted verbatim).
pub(super) fn glyph_typst(c: char) -> Option<&'static str> {
    GLYPH_TYPST.get(&c).copied()
}

pub(super) fn command_str(name: &str) -> Option<String> {
    if let Some(s) = spacing_str(name) {
        return Some(s.to_string());
    }
    if let Some(g) = greek_str(name) {
        return Some(g.to_string());
    }
    if let Some(f) = function_str(name) {
        return Some(f.to_string());
    }
    typst_symbol(name).map(ToString::to_string)
}

#[allow(clippy::match_same_arms)]
fn spacing_str(name: &str) -> Option<&'static str> {
    let s = match name {
        "," => "thin",
        ":" | ">" | " " => "med",
        ";" => "#h(0em)",
        "!" => "#h(-1em)",
        "medspace" => "space.med",
        "enspace" => "#h(0em)",
        "quad" => "quad",
        "qquad" => "#h(2em)",
        _ => return None,
    };
    Some(s)
}

fn greek_str(name: &str) -> Option<&'static str> {
    GREEK_TYPST_MAP.get(name).copied()
}

fn function_str(name: &str) -> Option<&'static str> {
    let f = match name {
        "sin" => "sin",
        "cos" => "cos",
        "tan" => "tan",
        "cot" => "cot",
        "sec" => "sec",
        "csc" => "csc",
        "arcsin" => "arcsin",
        "arccos" => "arccos",
        "arctan" => "arctan",
        "sinh" => "sinh",
        "cosh" => "cosh",
        "tanh" => "tanh",
        "coth" => "coth",
        "log" => "log",
        "ln" => "ln",
        "lg" => "lg",
        "exp" => "exp",
        "deg" => "deg",
        "dim" => "dim",
        "hom" => "hom",
        "ker" => "ker",
        "arg" => "arg",
        "lim" => "lim",
        "limsup" => "limsup",
        "liminf" => "liminf",
        "max" => "max",
        "min" => "min",
        "sup" => "sup",
        "inf" => "inf",
        "det" => "det",
        "gcd" => "gcd",
        "Pr" => "Pr",
        _ => return None,
    };
    Some(f)
}

/// The Typst name for a TeX math symbol command.
fn typst_symbol(name: &str) -> Option<&'static str> {
    SYMBOL_TYPST_MAP.get(name).copied()
}

/// The Typst name for each TeX math symbol command, as an iterable table. Both the forward
/// lookup [`typst_symbol`] and the codepoint-to-Typst reverse map ([`super::symbols`]) read
/// from this single source, so the two directions can never drift apart.
pub(crate) const SYMBOL_TYPST: &[(&str, &str)] = &[
    ("Aries", "\u{2648}"),
    ("Bbbk", "\u{1D55C}"),
    ("Box", "square.stroked"),
    ("Bumpeq", "\u{224E}"),
    ("Cap", "inter.double"),
    ("CheckedBox", "ballot.check"),
    ("Colon", "colon.double"),
    ("Cup", "union.double"),
    ("DD", "\u{2145}"),
    ("Diamond", "diamond.stroked"),
    ("Doteq", "eq.dots"),
    ("Downarrow", "arrow.b.double"),
    ("Finv", "\u{2132}"),
    ("Game", "\u{2141}"),
    ("Gemini", "\u{264A}"),
    ("Im", "Im"),
    ("Join", "\u{22C8}"),
    ("Leftarrow", "arrow.l.double"),
    ("Leftrightarrow", "arrow.l.r.double"),
    ("Leo", "\u{264C}"),
    ("Libra", "\u{264E}"),
    ("Lleftarrow", "arrow.l.triple"),
    ("Longleftarrow", "arrow.l.double"),
    ("Longleftrightarrow", "arrow.l.r.double"),
    ("Longrightarrow", "arrow.r.double"),
    ("Lsh", "\u{21B0}"),
    ("Pluto", "\u{2647}"),
    ("Re", "Re"),
    ("Rightarrow", "arrow.r.double"),
    ("Rrightarrow", "arrow.r.triple"),
    ("Rsh", "\u{21B1}"),
    ("Scorpio", "\u{264F}"),
    ("Square", "ballot"),
    ("Subset", "subset.double"),
    ("Sun", "sun"),
    ("Supset", "supset.double"),
    ("Taurus", "\u{2649}"),
    ("Uparrow", "arrow.t.double"),
    ("Updownarrow", "arrow.t.b.double"),
    ("Vdash", "forces"),
    ("Vert", "bar.v.double"),
    ("Vvdash", "\u{22AA}"),
    ("XBox", "ballot.cross"),
    ("aleph", "\u{2135}"),
    ("amalg", "product.co"),
    ("anchor", "\u{2693}"),
    ("angle", "angle"),
    ("approx", "approx"),
    ("approxeq", "approx.eq"),
    ("approxident", "tilde.triple"),
    ("ast", "*"),
    ("astrosun", "sun"),
    ("asymp", "asymp"),
    ("backcong", "tilde.rev.equiv"),
    ("backepsilon", "epsilon.alt.rev"),
    ("backprime", "prime.rev"),
    ("backsim", "tilde.rev"),
    ("backsimeq", "tilde.eq.rev"),
    ("backslash", "without"),
    ("barwedge", "\u{2305}"),
    ("because", "because"),
    ("beth", "\u{2136}"),
    ("between", "\u{226C}"),
    ("bigcap", "inter.big"),
    ("bigcirc", "circle.stroked"),
    ("bigcup", "union.big"),
    ("bigcupdot", "union.dot.big"),
    ("bigodot", "dot.o.big"),
    ("bigoplus", "xor.big"),
    ("bigotimes", "times.o.big"),
    ("bigsqcap", "inter.sq.big"),
    ("bigsqcup", "union.sq.big"),
    ("bigtimes", "times.big"),
    ("bigstar", "star.filled"),
    ("bigtriangledown", "triangle.stroked.b"),
    ("bigtriangleup", "triangle.stroked.t"),
    ("biguplus", "union.plus.big"),
    ("bigvee", "or.big"),
    ("bigwedge", "and.big"),
    ("biohazard", "\u{2623}"),
    ("blacklozenge", "lozenge.filled.medium"),
    ("blacksmiley", "\u{263B}"),
    ("blacksquare", "square.filled.medium"),
    ("blacktriangleleft", "triangle.filled.small.l"),
    ("blacktriangleright", "triangle.filled.small.r"),
    ("bot", "tack.t"),
    ("bowtie", "\u{22C8}"),
    ("boxdot", "dot.square"),
    ("boxminus", "minus.square"),
    ("boxplus", "plus.square"),
    ("boxtimes", "times.square"),
    ("bullet", "bullet"),
    ("bumpeq", "\u{224F}"),
    ("cap", "inter"),
    ("cdot", "dot.op"),
    ("cdotp", "dot.c"),
    ("cdots", "dots.h.c"),
    ("centerdot", "\u{2B1D}"),
    ("checkmark", "checkmark"),
    ("circeq", "\u{2257}"),
    ("circlearrowleft", "arrow.ccw"),
    ("circlearrowright", "arrow.cw"),
    ("circledR", "trademark.registered"),
    ("circledast", "convolve.o"),
    ("circledcirc", "compose.o"),
    ("circledequal", "eq.o"),
    ("circledparallel", "parallel.o"),
    ("circ", "compose"),
    ("clubsuit", "suit.club.filled"),
    ("varclubsuit", "suit.club.stroked"),
    ("varheartsuit", "suit.heart.filled"),
    ("vardiamondsuit", "suit.diamond.filled"),
    ("varspadesuit", "suit.spade.stroked"),
    ("rightmoon", "\u{263D}"),
    ("leftmoon", "\u{263E}"),
    ("sun", "\u{263C}"),
    ("colon", ":"),
    ("coloneqq", "colon.eq"),
    ("eqqcolon", "eq.colon"),
    ("Coloneqq", "colon.double.eq"),
    ("coloneq", "colon.eq"),
    ("Coloneq", "colon.double.eq"),
    ("eqcolon", "eq.colon"),
    ("notni", "in.rev.not"),
    ("leqq", "lt.equiv"),
    ("geqq", "gt.equiv"),
    ("lneqq", "lt.nequiv"),
    ("gneqq", "gt.nequiv"),
    ("gtreqqless", "\u{2A8C}"),
    ("lesseqqgtr", "\u{2A8B}"),
    ("complement", "complement"),
    ("cong", "tilde.equiv"),
    ("coprod", "product.co"),
    ("cup", "union"),
    ("curlyeqprec", "eq.prec"),
    ("curlyeqsucc", "eq.succ"),
    ("curlyvee", "or.curly"),
    ("curlywedge", "and.curly"),
    ("curvearrowleft", "arrow.ccw.half"),
    ("curvearrowright", "arrow.cw.half"),
    ("dag", "dagger"),
    ("dagger", "dagger"),
    ("daleth", "\u{2138}"),
    ("dashcolon", "dash.colon"),
    ("dashleftarrow", "arrow.l.dashed"),
    ("dashrightarrow", "arrow.r.dashed"),
    ("dashv", "tack.l"),
    ("ddag", "dagger.double"),
    ("dd", "\u{2146}"),
    ("ddagger", "dagger.double"),
    ("ddots", "dots.down"),
    ("diamond", "diamond.stroked.small"),
    ("diamondsuit", "suit.diamond.stroked"),
    ("digamma", "digamma"),
    ("div", "div"),
    ("divideontimes", "times.div"),
    ("doteq", "\u{2250}"),
    ("doteqdot", "eq.dots"),
    ("dotminus", "minus.dot"),
    ("dots", "dots.h"),
    ("dotsb", "dots.h.c"),
    ("dotsc", "dots.h"),
    ("dotsi", "dots.h.c"),
    ("dotsm", "dots.h.c"),
    ("dotso", "dots.h"),
    ("doublebarwedge", "\u{2306}"),
    ("downarrow", "arrow.b"),
    ("downdownarrows", "arrows.bb"),
    ("downharpoonleft", "harpoon.bl"),
    ("downharpoonright", "harpoon.br"),
    ("earth", "earth.alt"),
    ("eighthnote", "note.eighth.alt"),
    ("ee", "\u{2147}"),
    ("ell", "ell"),
    ("emptyset", "nothing"),
    ("eqcirc", "\u{2256}"),
    ("eqgtr", "eq.gt"),
    ("eqless", "eq.lt"),
    ("eqsim", "minus.tilde"),
    ("eqslantgtr", "\u{2A96}"),
    ("eqslantless", "\u{2A95}"),
    ("equiv", "equiv"),
    ("eth", "\u{F0}"),
    ("euro", "euro"),
    ("exists", "exists"),
    ("fallingdotseq", "eq.dots.down"),
    ("female", "venus"),
    ("flat", "flat"),
    ("forall", "forall"),
    ("frown", "frown"),
    ("frownie", "\u{2639}"),
    ("ge", "gt.eq"),
    ("geq", "gt.eq"),
    ("geqslant", "gt.eq"),
    ("gescc", "\u{2AA9}"),
    ("gets", "arrow.l"),
    ("gg", "gt.double"),
    ("ggg", "gt.triple"),
    ("gimel", "\u{2137}"),
    ("gnapprox", "gt.napprox"),
    ("gneq", "gt.neq"),
    ("gnsim", "gt.ntilde"),
    ("gtrdot", "gt.dot"),
    ("gtreqless", "gt.eq.lt"),
    ("gtrless", "gt.lt"),
    ("gtrsim", "gt.tilde"),
    ("hbar", "\u{210F}"),
    ("hdots", "dots.h"),
    ("heartsuit", "suit.heart.stroked"),
    ("hookleftarrow", "arrow.l.hook"),
    ("hookrightarrow", "arrow.r.hook"),
    ("hslash", "\u{210F}"),
    ("iff", "arrow.l.r.double"),
    ("iiint", "integral.triple"),
    ("iint", "integral.double"),
    ("ii", "\u{2148}"),
    ("imath", "dotless.i"),
    ("impliedby", "arrow.l.double.long"),
    ("implies", "arrow.r.double.long"),
    ("in", "in"),
    ("infty", "oo"),
    ("int", "integral"),
    ("intercal", "\u{22BA}"),
    ("jj", "\u{2149}"),
    ("jmath", "dotless.j"),
    ("jupiter", "jupiter"),
    ("lAngle", "chevron.l.double"),
    ("lBrace", "brace.l.stroked"),
    ("lVert", "parallel"),
    ("land", "and"),
    ("langle", "chevron.l"),
    ("lbrace", "{"),
    ("lbrack", "\\["),
    ("lceil", "ceil.l"),
    ("ldots", "dots.h"),
    ("le", "lt.eq"),
    ("leadsto", "\u{2933}"),
    ("leftarrow", "arrow.l"),
    ("leftharpoondown", "harpoon.lb"),
    ("leftharpoonup", "harpoon.lt"),
    ("leftleftarrows", "arrows.ll"),
    ("leftrightarrow", "arrow.l.r"),
    ("leftrightharpoons", "harpoons.ltrb"),
    ("leftrightsquigarrow", "arrow.l.r.wave"),
    ("leftthreetimes", "times.three.l"),
    ("leq", "lt.eq"),
    ("leqslant", "lt.eq"),
    ("lescc", "\u{2AA8}"),
    ("lessdot", "lt.dot"),
    ("lesseqgtr", "lt.eq.gt"),
    ("lessgtr", "lt.gt"),
    ("lesssim", "lt.tilde"),
    ("lfloor", "floor.l"),
    ("lhd", "lt.tri"),
    ("ll", "lt.double"),
    ("lll", "lt.triple"),
    ("lneq", "lt.neq"),
    ("lnapprox", "lt.napprox"),
    ("lnot", "not"),
    ("lnsim", "lt.ntilde"),
    ("longleftarrow", "arrow.l"),
    ("longleftrightarrow", "arrow.l.r"),
    ("longmapsto", "mapsto"),
    ("longrightarrow", "arrow.r"),
    ("lightning", "arrow.zigzag"),
    ("looparrowleft", "arrow.l.loop"),
    ("looparrowright", "arrow.r.loop"),
    ("lor", "or"),
    ("lozenge", "lozenge.stroked"),
    ("lparen", "\\("),
    ("ltimes", "times.l"),
    ("lvert", "\\|"),
    ("male", "mars"),
    ("maltese", "maltese"),
    ("mapsto", "mapsto"),
    ("mapsfrom", "arrow.l.bar"),
    ("Mapsto", "arrow.r.double.bar"),
    ("Mapsfrom", "arrow.l.double.bar"),
    ("longmapsfrom", "arrow.l.long.bar"),
    ("measuredangle", "angle.arc"),
    ("mercury", "mercury"),
    ("mho", "Omega.inv"),
    ("mid", "divides"),
    ("models", "tack.r.double"),
    ("mp", "minus.plus"),
    ("multimap", "multimap"),
    ("nLeftarrow", "arrow.l.double.not"),
    ("nLeftrightarrow", "arrow.l.r.double.not"),
    ("nRightarrow", "arrow.r.double.not"),
    ("nVDash", "\u{22AF}"),
    ("nVdash", "forces.not"),
    ("nabla", "nabla"),
    ("napprox", "approx.not"),
    ("nasymp", "asymp.not"),
    ("natural", "natural"),
    ("ncong", "tilde.equiv.not"),
    ("ne", "eq.not"),
    ("nearrow", "arrow.tr"),
    ("neg", "not"),
    ("neptune", "neptune"),
    ("neq", "eq.not"),
    ("nequiv", "equiv.not"),
    ("nexists", "exists.not"),
    ("ngeq", "gt.eq.not"),
    ("ngeqslant", "gt.eq.not"),
    ("ngtr", "gt.not"),
    ("ngtrsim", "gt.tilde.not"),
    ("ni", "in.rev"),
    ("nin", "in.not"),
    ("nleftarrow", "arrow.l.not"),
    ("nleftrightarrow", "arrow.l.r.not"),
    ("nleq", "lt.eq.not"),
    ("nleqslant", "lt.eq.not"),
    ("nlessgtr", "lt.gt.not"),
    ("nlesssim", "lt.tilde.not"),
    ("nless", "lt.not"),
    ("nmid", "divides.not"),
    ("notin", "in.not"),
    ("nparallel", "parallel.not"),
    ("nprec", "prec.not"),
    ("npreccurlyeq", "prec.curly.eq.not"),
    ("npreceq", "prec.curly.eq.not"),
    ("nrightarrow", "arrow.r.not"),
    ("nsim", "tilde.not"),
    ("nsime", "tilde.eq.not"),
    ("nsimeq", "tilde.eq.not"),
    ("nsubset", "subset.not"),
    ("nsubseteq", "subset.eq.not"),
    ("nsucc", "succ.not"),
    ("nsupset", "supset.not"),
    ("nsupseteq", "supset.eq.not"),
    ("nsucccurlyeq", "succ.curly.eq.not"),
    ("nsucceq", "succ.curly.eq.not"),
    ("ntriangleleft", "lt.tri.not"),
    ("ntrianglelefteq", "lt.tri.eq.not"),
    ("ntriangleright", "gt.tri.not"),
    ("ntrianglerighteq", "gt.tri.eq.not"),
    ("nvDash", "tack.r.double.not"),
    ("nvdash", "tack.r.not"),
    ("nwarrow", "arrow.tl"),
    ("odot", "dot.o"),
    ("oint", "integral.cont"),
    ("oiint", "integral.surf"),
    ("oiiint", "integral.vol"),
    ("sqint", "integral.square"),
    ("fint", "integral.slash"),
    ("varointclockwise", "integral.cont.cw"),
    ("ointctrclockwise", "integral.cont.ccw"),
    ("awint", "integral.ccw"),
    ("iiiint", "integral.quad"),
    ("varprod", "times.big"),
    ("leftarrowtail", "arrow.l.tail"),
    ("subseteqq", "\u{2AC5}"),
    ("supseteqq", "\u{2AC6}"),
    ("gtrapprox", "gt.approx"),
    ("lessapprox", "lt.approx"),
    ("ngtrless", "gt.lt.not"),
    ("twoheadleftarrow", "arrow.l.twohead"),
    ("leftrightarrows", "arrows.lr"),
    ("circleddash", "dash.o"),
    ("dotplus", "plus.dot"),
    ("blacktriangle", "triangle.filled.small.t"),
    ("blacktriangledown", "triangle.filled.small.b"),
    ("ulcorner", "corner.l.t"),
    ("urcorner", "corner.r.t"),
    ("llcorner", "corner.l.b"),
    ("lrcorner", "corner.r.b"),
    ("lmoustache", "mustache.l"),
    ("rmoustache", "mustache.r"),
    ("lgroup", "paren.l.flat"),
    ("rgroup", "paren.r.flat"),
    ("llbracket", "bracket.l.stroked"),
    ("rrbracket", "bracket.r.stroked"),
    ("llparenthesis", "paren.l.closed"),
    ("rrparenthesis", "paren.r.closed"),
    ("diameter", "diameter"),
    ("obar", "\u{233D}"),
    ("ogreaterthan", "gt.o"),
    ("olessthan", "lt.o"),
    ("ominus", "minus.o"),
    ("oplus", "xor"),
    ("oslash", "slash.o"),
    ("otimes", "times.o"),
    ("owns", "in.rev"),
    ("parallel", "parallel"),
    ("partial", "partial"),
    ("pencil", "\u{270E}"),
    ("perp", "perp"),
    ("pitchfork", "\u{22D4}"),
    ("pm", "plus.minus"),
    ("pounds", "pound"),
    ("prec", "prec"),
    ("precapprox", "prec.approx"),
    ("preccurlyeq", "prec.curly.eq"),
    ("preceq", "prec.curly.eq"),
    ("precnapprox", "prec.napprox"),
    ("precneqq", "prec.nequiv"),
    ("precnsim", "prec.ntilde"),
    ("precsim", "prec.tilde"),
    ("prime", "'"),
    ("prod", "product"),
    ("propto", "prop"),
    ("quarternote", "note.quarter.alt"),
    ("rAngle", "chevron.r.double"),
    ("rBrace", "brace.r.stroked"),
    ("rVert", "parallel"),
    ("rangle", "chevron.r"),
    ("rbrace", "}"),
    ("rbrack", "\\]"),
    ("radiation", "\u{2622}"),
    ("rceil", "ceil.r"),
    ("recycle", "\u{267B}"),
    ("rfloor", "floor.r"),
    ("rhd", "gt.tri"),
    ("restriction", "harpoon.tr"),
    ("rightarrow", "arrow.r"),
    ("rightarrowtail", "arrow.r.tail"),
    ("rightharpoondown", "harpoon.rb"),
    ("rightharpoonup", "harpoon.rt"),
    ("rightleftarrows", "arrows.rl"),
    ("rightleftharpoons", "harpoons.rtlb"),
    ("rightrightarrows", "arrows.rr"),
    ("rightsquigarrow", "arrow.r.squiggly"),
    ("rightthreetimes", "times.three.r"),
    ("risingdotseq", "eq.dots.up"),
    ("rparen", "\\)"),
    ("rtimes", "times.r"),
    ("rvert", "\\|"),
    ("saturn", "saturn"),
    ("searrow", "arrow.br"),
    ("setminus", "\\\\"),
    ("sharp", "sharp"),
    ("sim", "tilde.op"),
    ("simeq", "tilde.eq"),
    ("simneqq", "tilde.nequiv"),
    ("skull", "\u{2620}"),
    ("smallsetminus", "without"),
    ("smallsmile", "smile"),
    ("smallfrown", "frown"),
    ("smile", "smile"),
    ("smiley", "\u{263A}"),
    ("spadesuit", "suit.spade.filled"),
    ("sphericalangle", "angle.spheric"),
    ("sqcap", "inter.sq"),
    ("sqcup", "union.sq"),
    ("sqsubset", "subset.sq"),
    ("sqsubseteq", "subset.eq.sq"),
    ("sqsupset", "supset.sq"),
    ("sqsupseteq", "supset.eq.sq"),
    ("square", "square.stroked.tiny"),
    ("star", "star.op"),
    ("strictfi", "\u{297C}"),
    ("strictif", "\u{297D}"),
    ("subset", "subset"),
    ("subseteq", "subset.eq"),
    ("subsetneq", "subset.neq"),
    ("subsetneqq", "\u{2ACB}"),
    ("succ", "succ"),
    ("succapprox", "succ.approx"),
    ("succcurlyeq", "succ.curly.eq"),
    ("succeq", "succ.curly.eq"),
    ("succnapprox", "succ.napprox"),
    ("succneqq", "succ.nequiv"),
    ("succnsim", "succ.ntilde"),
    ("succsim", "succ.tilde"),
    ("sum", "sum"),
    ("supset", "supset"),
    ("supseteq", "supset.eq"),
    ("supsetneq", "supset.neq"),
    ("supsetneqq", "\u{2ACC}"),
    ("swarrow", "arrow.bl"),
    ("therefore", "therefore"),
    ("times", "times"),
    ("to", "arrow.r"),
    ("top", "top"),
    ("triangle", "triangle.stroked.t"),
    ("triangledown", "triangle.stroked.small.b"),
    ("triangleleft", "lt.tri"),
    ("trianglelefteq", "lt.tri.eq"),
    ("triangleq", "eq.delta"),
    ("triangleright", "gt.tri"),
    ("trianglerighteq", "gt.tri.eq"),
    ("twoheadrightarrow", "arrow.r.twohead"),
    ("twonotes", "note.eighth.beamed"),
    ("unlhd", "lt.tri.eq"),
    ("unrhd", "gt.tri.eq"),
    ("uparrow", "arrow.t"),
    ("updownarrow", "arrow.t.b"),
    ("upharpoonleft", "harpoon.tl"),
    ("upharpoonright", "harpoon.tr"),
    ("uplus", "union.plus"),
    ("upuparrows", "arrows.tt"),
    ("uranus", "uranus.alt"),
    ("vDash", "tack.r.double"),
    ("varkappa", "\u{1D718}"),
    ("varnothing", "diameter"),
    ("varpropto", "prop"),
    ("varsubsetneq", "subset.neq"),
    ("vartriangle", "triangle.stroked.small.t"),
    ("vartriangleleft", "lt.tri"),
    ("vartriangleright", "gt.tri"),
    ("vdash", "tack.r"),
    ("vdots", "dots.v"),
    ("vee", "or"),
    ("veebar", "\u{22BB}"),
    ("vert", "\\|"),
    ("wasylozenge", "\u{2311}"),
    ("wedge", "and"),
    ("wp", "\u{2118}"),
    ("wr", "wreath"),
    ("yen", "yuan"),
    ("yinyang", "\u{262F}"),
    // dollar, hash, and underscore are escaped so they are not read as code/script syntax
    ("{", "{"),
    ("}", "}"),
    ("|", "parallel"),
    ("%", "%"),
    ("$", "\\$"),
    ("#", "\\#"),
    ("&", "&"),
    ("_", "\\_"),
];

/// The Typst name for each Greek-letter command, as an iterable table feeding both the forward
/// lookup [`greek_str`] and the codepoint reverse map.
pub(crate) const GREEK_TYPST: &[(&str, &str)] = &[
    ("alpha", "alpha"),
    ("beta", "beta"),
    ("gamma", "gamma"),
    ("delta", "delta"),
    ("epsilon", "epsilon.alt"),
    ("varepsilon", "epsilon"),
    ("zeta", "zeta"),
    ("eta", "eta"),
    ("theta", "theta"),
    ("vartheta", "theta.alt"),
    ("iota", "iota"),
    ("kappa", "kappa"),
    ("lambda", "lambda"),
    ("mu", "mu"),
    ("nu", "nu"),
    ("xi", "xi"),
    ("omicron", "omicron"),
    ("pi", "pi"),
    ("varpi", "pi.alt"),
    ("rho", "rho"),
    ("varrho", "\u{1D71A}"),
    ("sigma", "sigma"),
    ("varsigma", "\u{1D70D}"),
    ("tau", "tau"),
    ("upsilon", "upsilon"),
    ("phi", "phi.alt"),
    ("varphi", "phi"),
    ("chi", "chi"),
    ("psi", "psi"),
    ("omega", "omega"),
    ("Gamma", "Gamma"),
    ("Delta", "Delta"),
    ("Theta", "Theta"),
    ("Lambda", "Lambda"),
    ("Xi", "Xi"),
    ("Pi", "Pi"),
    ("Sigma", "Sigma"),
    ("Upsilon", "Upsilon"),
    ("Phi", "Phi"),
    ("Psi", "Psi"),
    ("Omega", "Omega"),
    // Capital Greek letters whose glyph is a Latin lookalike are spelled by name.
    ("Alpha", "Alpha"),
    ("Beta", "Beta"),
    ("Epsilon", "Epsilon"),
    ("Zeta", "Zeta"),
    ("Eta", "Eta"),
    ("Iota", "Iota"),
    ("Kappa", "Kappa"),
    ("Mu", "Mu"),
    ("Nu", "Nu"),
    ("Omicron", "Omicron"),
    ("Rho", "Rho"),
    ("Tau", "Tau"),
    ("Chi", "Chi"),
    ("upalpha", "alpha"),
    ("upbeta", "beta"),
    ("upgamma", "gamma"),
    ("updelta", "delta"),
    ("upepsilon", "epsilon"),
    ("upzeta", "zeta"),
    ("upeta", "eta"),
    ("uptheta", "theta"),
    ("upiota", "iota"),
    ("upkappa", "kappa"),
    ("uplambda", "lambda"),
    ("upmu", "mu"),
    ("upnu", "nu"),
    ("upxi", "xi"),
    ("upomicron", "omicron"),
    ("uppi", "pi"),
    ("uprho", "rho"),
    ("upsigma", "sigma"),
    ("uptau", "tau"),
    ("upupsilon", "upsilon"),
    ("upphi", "phi.alt"),
    ("upchi", "chi"),
    ("uppsi", "psi"),
    ("upomega", "omega"),
];
