//! Renders the CLI reference by converting the binary's own man page with carta itself.
//!
//! `carta --man` emits roff from the clap command definition; carta's man reader and GFM writer
//! turn that into the published page. The reference therefore describes the binary that exists,
//! not a hand-maintained copy of it.

use std::error::Error;
use std::path::Path;
use std::process::Command;

use carta::{ReaderOptions, WrapMode, WriterOptions, convert_text};

const FRONT_MATTER: &str = "---\ntitle: CLI reference\ndescription: Every carta command-line flag, generated from the binary's own help text.\nsidebar:\n  order: 2\n---\n\n<!-- Generated by tools/docgen from `carta --man`. Do not edit. -->\n\n:::note[Converted by carta]\nThis page is `carta --man` read back in and converted to Markdown by carta itself. Pretty neat!\n:::\n\n";

/// The full text of the generated CLI reference page.
pub fn reference(root: &Path) -> Result<String, Box<dyn Error>> {
    let roff = man_page(root)?;
    let mut writer_options = WriterOptions::default();
    // One line per paragraph: the page is read rendered, and unwrapped source diffs cleanly.
    writer_options.wrap = WrapMode::None;

    let markdown = convert_text(
        "man",
        "gfm",
        &roff,
        &ReaderOptions::default(),
        &writer_options,
    )?;

    Ok(format!(
        "{FRONT_MATTER}{}\n",
        demote_headings(&code_spans(&markdown))
    ))
}

/// Builds the workspace's `carta` and runs `--man` on it.
///
/// Cargo both builds and runs, so the roff always comes from the current sources. Resolving a
/// path under `target/` instead would reuse whichever artifact happened to be lying there, and a
/// stale one describes flags the binary no longer has. Cargo writes its own progress to stderr,
/// leaving stdout to the man page alone.
fn man_page(root: &Path) -> Result<String, Box<dyn Error>> {
    let output = Command::new(cargo())
        .args(["run", "--quiet", "-p", "carta", "--", "--man"])
        .current_dir(root)
        .output()?;
    if !output.status.success() {
        return Err(format!(
            "`cargo run -p carta -- --man` failed:\n{}",
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn cargo() -> String {
    std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned())
}

/// Restores the backticks the help text writes around code as Markdown code spans.
///
/// roff has no code-span concept, so a backtick reaches the man page as an ordinary character and
/// the Markdown writer escapes it to keep it one. Here the intent behind those characters is known,
/// so each balanced pair becomes the span the help text meant, and the escapes inside it are undone
/// because a code span needs none. An unpaired backtick is left exactly as the writer emitted it.
fn code_spans(markdown: &str) -> String {
    let mut out = String::with_capacity(markdown.len());
    let mut rest = markdown;

    while let Some(open) = rest.find("\\`") {
        let (before, from_open) = rest.split_at(open);
        out.push_str(before);
        let Some(inner) = from_open.strip_prefix("\\`") else {
            break;
        };
        match inner.find("\\`") {
            Some(close) => {
                let (span, tail) = inner.split_at(close);
                out.push('`');
                out.push_str(&unescape(span));
                out.push('`');
                rest = tail.strip_prefix("\\`").unwrap_or(tail);
            }
            None => {
                out.push_str("\\`");
                rest = inner;
            }
        }
    }

    out.push_str(rest);
    out
}

/// Drops the backslash from every escaped ASCII punctuation character.
fn unescape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut characters = text.chars();

    while let Some(character) = characters.next() {
        if character != '\\' {
            out.push(character);
            continue;
        }
        match characters.next() {
            Some(escaped) if escaped.is_ascii_punctuation() => out.push(escaped),
            Some(other) => {
                out.push('\\');
                out.push(other);
            }
            None => out.push('\\'),
        }
    }

    out
}

/// Shifts every heading down one level so the page's own title stays the only `h1`, and drops the
/// man-page convention of setting section names in capitals.
fn demote_headings(markdown: &str) -> String {
    markdown
        .lines()
        .map(|line| match line.split_once(' ') {
            Some((hashes, title))
                if hashes.starts_with('#') && hashes.bytes().all(|b| b == b'#') =>
            {
                format!("#{hashes} {}", sentence_case(title))
            }
            _ => line.to_owned(),
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Lowercases a heading that is set entirely in capitals, keeping its first letter.
fn sentence_case(title: &str) -> String {
    if title.chars().any(char::is_lowercase) {
        return title.to_owned();
    }
    let mut characters = title.chars();
    match characters.next() {
        Some(first) => {
            first.to_uppercase().collect::<String>() + &characters.as_str().to_lowercase()
        }
        None => String::new(),
    }
}
