//! Renders the CLI reference by converting the binary's own man page with carta itself.
//!
//! `carta --man` emits roff from the clap command definition; carta's man reader and GFM writer
//! turn that into the published page. The reference therefore describes the binary that exists,
//! not a hand-maintained copy of it.

use std::error::Error;
use std::path::{Path, PathBuf};
use std::process::Command;

use carta::{ReaderOptions, WrapMode, WriterOptions, convert_text};

const FRONT_MATTER: &str = "---\ntitle: CLI reference\ndescription: Every carta command-line flag, generated from the binary's own help text.\nsidebar:\n  order: 2\n---\n\n<!-- Generated by tools/docgen from `carta --man`. Do not edit. -->\n\n";

/// The full text of the generated CLI reference page.
pub fn reference(root: &Path) -> Result<String, Box<dyn Error>> {
    let roff = man_page(root)?;
    let mut writer_options = WriterOptions::default();
    // One line per paragraph: the page is read rendered, and unwrapped source diffs cleanly.
    writer_options.wrap = WrapMode::None;

    let markdown = convert_text(
        "man",
        "gfm",
        &roff,
        &ReaderOptions::default(),
        &writer_options,
    )?;

    Ok(format!("{FRONT_MATTER}{}\n", demote_headings(&markdown)))
}

/// Runs `carta --man`, building the binary first if no build has produced one yet.
fn man_page(root: &Path) -> Result<String, Box<dyn Error>> {
    let binary = locate_binary(root).map_or_else(
        || {
            let status = Command::new(cargo())
                .args(["build", "--quiet", "-p", "carta"])
                .current_dir(root)
                .status()?;
            if !status.success() {
                return Err("failed to build the carta binary for the CLI reference".into());
            }
            locate_binary(root).ok_or_else(|| {
                Box::<dyn Error>::from("carta built but no binary was found under target/")
            })
        },
        Ok,
    )?;

    let output = Command::new(&binary).arg("--man").output()?;
    if !output.status.success() {
        return Err(format!("{} --man failed", binary.display()).into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn locate_binary(root: &Path) -> Option<PathBuf> {
    let name = if cfg!(windows) { "carta.exe" } else { "carta" };
    ["release", "debug"]
        .iter()
        .map(|profile| root.join("target").join(profile).join(name))
        .find(|path| path.is_file())
}

fn cargo() -> String {
    std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned())
}

/// Shifts every heading down one level, so the page's own title stays the only `h1`.
fn demote_headings(markdown: &str) -> String {
    markdown
        .lines()
        .map(|line| {
            if line.starts_with('#') {
                format!("#{line}")
            } else {
                line.to_owned()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
