//! Renders `docs/STATUS.md` from the status data.

use crate::model::{Direction, FAMILIES, Format, Status, Support};

/// The do-not-edit banner every generated Markdown file opens with, naming its own source.
pub fn generated_header(source: &str) -> String {
    format!("<!-- Generated by tools/docgen from {source}. Do not edit. -->")
}

const WRAP_COLUMNS: usize = 100;

const LEGEND: &str = "✅ usable (basically done, any remaining parity gaps are minor and unlikely to affect regular use) · 🚧 in development (large parity gaps or breaking issues, not recommended for use yet) · ❌ not started · ➖ not applicable (pandoc has no such direction)";

const ENTRY_NOTE: &str = "Each entry lists only what is still missing or known to diverge. An entry with no list has no tracked gap.";

const EXTENSIONS_INTRO: &str = "Reader-side toggles on the CommonMark engine. The enum defines {count} names; the reader branches on the **Supported** set below and treats every other name within a format's accepted set as a recorded no-op toggle, so a format spec naming one parses and records it rather than aborting. Each format declares the set of extensions it accepts: exactly the names `--list-extensions=<format>` prints, with the sign each carries when the format is read (or written, where it only writes). A `+`/`-` toggle naming anything outside that set is rejected.";

const PARITY_GAPS_INTRO: &str =
    "Constructs the supported extensions read, each with one narrow case that still diverges.";

const NOT_MODELED_INTRO: &str = "These names have an enum variant, so a format spec may toggle them and the toggle is recorded, but the reader does not yet branch on the construct (notable, non-exhaustive):";

const NOT_MODELED_NOTE: &str =
    "(`shortcut_reference_links` is already covered by the CommonMark engine.)";

const FEATURES_INTRO: &str = "Notes list gaps and limitations only.";

/// The full text of `docs/STATUS.md`.
pub fn status_markdown(status: &Status) -> String {
    let mut out = String::new();
    out.push_str(&generated_header("docs/status.toml"));
    out.push_str("\n\n# carta status\n\n");
    out.push_str(&format!(
        "Per-format status including extension coverage for carta. Measured against pinned pandoc **{}** (`pandoc-api-version {}`).\n\n",
        status.meta.oracle_version, status.meta.ast_version
    ));
    out.push_str(LEGEND);
    out.push_str("\n\n");
    out.push_str(ENTRY_NOTE);
    out.push_str("\n\n---\n\n");

    glance(&mut out, status);
    direction_section(&mut out, status, Direction::Read, "Readers");
    out.push_str("---\n\n");
    direction_section(&mut out, status, Direction::Write, "Writers");
    out.push_str("---\n\n");
    extensions(&mut out, status);
    out.push_str("---\n\n");
    features(&mut out, status);
    out
}

fn glance(out: &mut String, status: &Status) {
    out.push_str("## Formats at a glance\n");
    let formats = status.sorted_formats();
    for (key, heading) in FAMILIES {
        let members: Vec<&&Format> = formats.iter().filter(|f| f.family == *key).collect();
        if members.is_empty() {
            continue;
        }
        out.push_str(&format!("\n### {heading}\n\n"));
        out.push_str("| Format | Reader | Writer |\n| --- | :---: | :---: |\n");
        for format in members {
            out.push_str(&format!(
                "| {} ({}) | {} | {} |\n",
                format.title,
                code_list(std::iter::once(format.name.as_str()).chain(alias_strs(format))),
                format.read.marker(),
                format.write.marker(),
            ));
        }
    }
    out.push('\n');
}

fn direction_section(out: &mut String, status: &Status, direction: Direction, heading: &str) {
    out.push_str(&format!("## {heading}\n\n"));
    let accepted = direction.registry_names();
    let mut previous_had_gaps = false;
    let mut first = true;

    for format in status.sorted_formats() {
        if !direction.support(format).ships() {
            continue;
        }
        let gaps = direction.gaps(format);
        if !first && (previous_had_gaps || !gaps.is_empty()) {
            out.push('\n');
        }
        let aliases: Vec<&str> = alias_strs(format)
            .filter(|alias| accepted.contains(alias))
            .collect();
        let suffix = if aliases.is_empty() {
            String::new()
        } else {
            format!(" (+ {})", code_list(aliases.into_iter()))
        };
        out.push_str(&format!(
            "### `{}`{suffix} {}\n",
            format.name,
            direction.support(format).marker()
        ));
        for gap in gaps {
            out.push_str(&wrap_with(gap, "- ", "  "));
            out.push('\n');
        }
        previous_had_gaps = !gaps.is_empty();
        first = false;
    }

    out.push('\n');
    out.push_str(&wrap(&format!(
        "**Not started:** {}.",
        not_started_list(status, direction)
    )));
    out.push_str("\n\n");
}

/// The roadmap names for one direction, with each alias compressed to the suffix it adds.
fn not_started_list(status: &Status, direction: Direction) -> String {
    let mut items: Vec<String> = status
        .formats
        .iter()
        .filter(|format| direction.support(format) == Support::NotStarted)
        .map(|format| {
            let suffixes: Vec<String> = format
                .aliases
                .iter()
                .map(|alias| {
                    alias
                        .strip_prefix(&format.name)
                        .unwrap_or(alias.as_str())
                        .to_owned()
                })
                .collect();
            if suffixes.is_empty() {
                format!("`{}`", format.name)
            } else {
                format!(
                    "`{}` (+ {})",
                    format.name,
                    code_list(suffixes.iter().map(String::as_str))
                )
            }
        })
        .collect();
    items.sort();
    items.join(", ")
}

fn extensions(out: &mut String, status: &Status) {
    out.push_str("## Extensions\n\n");
    out.push_str(&wrap(
        &EXTENSIONS_INTRO.replace("{count}", &carta::Extension::COUNT.to_string()),
    ));
    out.push_str("\n\n");
    out.push_str(&wrap(&format!(
        "**Supported:** {}.",
        code_list(status.extensions.supported.iter().map(String::as_str))
    )));

    out.push_str("\n\n### Known parity gaps\n\n");
    out.push_str(PARITY_GAPS_INTRO);
    out.push_str("\n\n| Extension(s) | Gap |\n| --- | --- |\n");
    for gap in &status.extensions.gaps {
        out.push_str(&format!(
            "| {} | {} |\n",
            code_list(gap.names.iter().map(String::as_str)),
            gap.description
        ));
    }

    out.push_str("\n### Recognized, behavior not yet modeled\n\n");
    out.push_str(&wrap(&format!(
        "{NOT_MODELED_INTRO} {}.\n{NOT_MODELED_NOTE}",
        code_list(
            status
                .extensions
                .recognized_not_modeled
                .iter()
                .map(String::as_str)
        )
    )));
    out.push_str("\n\n");
}

fn features(out: &mut String, status: &Status) {
    out.push_str("## Cross-cutting features\n\n");
    out.push_str(FEATURES_INTRO);
    out.push_str("\n\n| Feature | Status | Notes |\n| --- | :---: | --- |\n");
    for feature in &status.features {
        let notes = if feature.notes.is_empty() {
            "—"
        } else {
            &feature.notes
        };
        out.push_str(&format!(
            "| {} | {} | {notes} |\n",
            feature.name,
            feature.status.marker()
        ));
    }
}

fn alias_strs(format: &Format) -> impl Iterator<Item = &str> {
    format.aliases.iter().map(String::as_str)
}

fn code_list<'a>(items: impl Iterator<Item = &'a str>) -> String {
    items
        .map(|item| format!("`{item}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Greedy word wrap at [`WRAP_COLUMNS`], preserving any hard line breaks already present.
pub fn wrap(text: &str) -> String {
    wrap_with(text, "", "")
}

/// [`wrap`] with a marker on the first line and a hanging indent on the rest.
fn wrap_with(text: &str, first_prefix: &str, continuation: &str) -> String {
    let mut wrapped: Vec<String> = Vec::new();
    for paragraph in text.split('\n') {
        let prefix = if wrapped.is_empty() {
            first_prefix
        } else {
            continuation
        };
        let mut line = String::from(prefix);
        let mut empty = true;
        for word in paragraph.split_whitespace() {
            if empty {
                line.push_str(word);
                empty = false;
            } else if line.chars().count() + 1 + word.chars().count() <= WRAP_COLUMNS {
                line.push(' ');
                line.push_str(word);
            } else {
                wrapped.push(std::mem::take(&mut line));
                line.push_str(continuation);
                line.push_str(word);
            }
        }
        wrapped.push(line);
    }
    wrapped.join("\n")
}
