//! Compresses the bundled syntax definitions into `OUT_DIR` and generates an index over them.
//!
//! Each `data/syntax/*.xml` file is deflate-compressed to keep the binary small; the raw XML is
//! decompressed and parsed lazily, the first time a language is used. The generated `bundled.rs`
//! carries each definition's metadata (name, short name, extensions, …) so language resolution and
//! listing never have to decompress anything.

// A failed build script should abort the build loudly; panicking and indexing are intended here.
#![allow(clippy::expect_used, clippy::panic, clippy::indexing_slicing)]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let syntax_dir = Path::new(&manifest_dir).join("data/syntax");
    let out_syntax = Path::new(&out_dir).join("syntax");
    fs::create_dir_all(&out_syntax).expect("create OUT_DIR/syntax");

    println!("cargo:rerun-if-changed=data/syntax");

    let mut entries: Vec<Entry> = Vec::new();
    let mut files: Vec<_> = fs::read_dir(&syntax_dir)
        .expect("read data/syntax")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "xml"))
        .collect();
    files.sort();

    for path in &files {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("utf-8 stem")
            .to_string();
        let xml = fs::read_to_string(path).unwrap_or_else(|_| panic!("read {}", path.display()));
        let compressed = miniz_oxide::deflate::compress_to_vec(xml.as_bytes(), 10);
        let out_file = out_syntax.join(format!("{stem}.deflate"));
        fs::write(&out_file, &compressed).expect("write compressed grammar");

        let meta = extract_metadata(&xml);
        let short = short_name(&stem);
        entries.push(Entry {
            stem,
            name: meta.name,
            short,
            extensions: meta.extensions,
            hidden: meta.hidden,
            priority: meta.priority,
        });
    }

    let mut generated = String::new();
    generated.push_str(
        "// Generated by build.rs. The compressed grammar bytes live alongside in OUT_DIR/syntax.\n",
    );
    generated.push_str("pub(crate) struct Bundled {\n");
    generated.push_str("    pub name: &'static str,\n");
    generated.push_str("    pub short: &'static str,\n");
    generated.push_str("    pub extensions: &'static [&'static str],\n");
    generated.push_str("    pub hidden: bool,\n");
    generated.push_str("    pub priority: i64,\n");
    generated.push_str("    pub data: &'static [u8],\n");
    generated.push_str("}\n\n");
    generated.push_str("pub(crate) static BUNDLED: &[Bundled] = &[\n");
    for e in &entries {
        let exts = e
            .extensions
            .iter()
            .map(|x| escape(x))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            generated,
            "    Bundled {{ name: {}, short: {}, extensions: &[{}], hidden: {}, priority: {}, \
             data: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/syntax/{}.deflate\")) }},",
            escape(&e.name),
            escape(&e.short),
            exts,
            e.hidden,
            e.priority,
            e.stem,
        );
    }
    generated.push_str("];\n");

    fs::write(Path::new(&out_dir).join("bundled.rs"), generated).expect("write bundled.rs");
}

struct Entry {
    stem: String,
    name: String,
    short: String,
    extensions: Vec<String>,
    hidden: bool,
    priority: i64,
}

struct Metadata {
    name: String,
    extensions: Vec<String>,
    hidden: bool,
    priority: i64,
}

/// The short name a definition resolves under: its file stem with word separators dropped and
/// lower-cased.
fn short_name(stem: &str) -> String {
    stem.chars()
        .filter(|c| c.is_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect()
}

fn extract_metadata(xml: &str) -> Metadata {
    let attrs = language_attrs(xml);
    let name = attrs.get("name").cloned().unwrap_or_default();
    let extensions = attrs
        .get("extensions")
        .map(|s| {
            s.split(';')
                .map(str::trim)
                .filter(|x| !x.is_empty())
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default();
    let hidden = attrs
        .get("hidden")
        .is_some_and(|v| matches!(v.as_str(), "1" | "true" | "True" | "TRUE"));
    let priority = attrs
        .get("priority")
        .and_then(|p| p.parse().ok())
        .unwrap_or(0);
    Metadata {
        name,
        extensions,
        hidden,
        priority,
    }
}

/// Extract the attributes of the `<language …>` opening tag with a light hand-rolled scan; the
/// build script does not pull in an XML crate for this.
fn language_attrs(xml: &str) -> BTreeMap<String, String> {
    let mut attrs = BTreeMap::new();
    let Some(start) = xml.find("<language") else {
        return attrs;
    };
    let after = &xml[start + "<language".len()..];
    let Some(end) = after.find('>') else {
        return attrs;
    };
    let body = &after[..end];
    let bytes: Vec<char> = body.chars().collect();
    let mut i = 0;
    while i < bytes.len() {
        while i < bytes.len() && bytes[i].is_whitespace() {
            i += 1;
        }
        let name_start = i;
        while i < bytes.len() && bytes[i] != '=' && !bytes[i].is_whitespace() {
            i += 1;
        }
        let key: String = bytes[name_start..i].iter().collect();
        while i < bytes.len() && bytes[i].is_whitespace() {
            i += 1;
        }
        if i < bytes.len() && bytes[i] == '=' {
            i += 1;
            while i < bytes.len() && bytes[i].is_whitespace() {
                i += 1;
            }
            if i < bytes.len() && (bytes[i] == '"' || bytes[i] == '\'') {
                let quote = bytes[i];
                i += 1;
                let val_start = i;
                while i < bytes.len() && bytes[i] != quote {
                    i += 1;
                }
                let value: String = bytes[val_start..i].iter().collect();
                if i < bytes.len() {
                    i += 1;
                }
                if !key.is_empty() {
                    attrs.insert(key, unescape_basic(&value));
                }
            }
        }
    }
    attrs
}

fn unescape_basic(s: &str) -> String {
    s.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
}

/// Render a string as a Rust string literal.
fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}
