#!/usr/bin/env bash
# Vendor the CommonMark specification used to drive the reader's differential tests.
#
# The spec is a public format specification (CC-BY-SA 4.0) — an allowed source of truth for this
# clean-room reimplementation. Its embedded examples are markdown *inputs* only; the expected output
# is regenerated by the pinned oracle binary, never taken from the spec's reference HTML. The file is
# committed (unlike the gitignored pandoc oracle) so the reader test corpus is reproducible offline.
#
# Re-run this only to bump the pinned spec version; edit SPEC_VERSION and commit the result.
set -euo pipefail

SPEC_VERSION="0.31.2"
REPO="commonmark/commonmark-spec"
DEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/crates/oxidoc-testkit/vendor/commonmark"

base="https://raw.githubusercontent.com/${REPO}/${SPEC_VERSION}"

mkdir -p "$DEST_DIR"
echo "Fetching CommonMark spec ${SPEC_VERSION} into ${DEST_DIR}"
curl -fsSL "${base}/spec.txt" -o "${DEST_DIR}/spec.txt"
curl -fsSL "${base}/LICENSE" -o "${DEST_DIR}/LICENSE"
printf '%s\n' "$SPEC_VERSION" > "${DEST_DIR}/VERSION"

examples="$(grep -c '^`\{32\} example' "${DEST_DIR}/spec.txt" || true)"
echo "Vendored spec.txt (${examples} examples), LICENSE, VERSION=${SPEC_VERSION}"
